### ISSUE TITLE
Pass AWS secret and access keys for setup

### ISSUE THREAD

**Issue by alanwill** [awslabs/aws-api-gateway-developer-portal#12]
Instead of having this rely on the default cli profile, is it feasible to either support a profile or have the setup utility prompt for a secret and access key?

**Comment by kahouieong** [comment]
It is possible to support a custom profile for the credential since the AWS JS SDK is supporting it. 
See [blog post](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/)

The way this tool is currently written only uses the default profile, but it should be very straight forward to add that support. 

For a quick and dirty way, you can add this to this [file](https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/scripts/post-configure.js#L11)
```javascript
var credentials = new AWS.SharedIniFileCredentials({profile: 'work-account'});
AWS.config.credentials = credentials;
```

Thanks,
-Ka Hou

**Comment by alanwill** [comment]
Thanks @kahouieong I just did that but when I try to deploy it's not reading the profile. Is there something else I need to do to have it take effect?

```
#!/usr/bin/env node
'use strict'

const fs = require('fs')
const path = require('path')
const AWS = require('aws-sdk')
const rootDir = path.resolve(__dirname, '..')
const packageJson = require(`${rootDir}/package.json`)
const primaryAwsRegion = packageJson.config.primaryAwsRegion

AWS.config.update({ region:primaryAwsRegion })
var credentials = new AWS.SharedIniFileCredentials({profile: 'work-account'});
AWS.config.credentials = credentials;

const cloudformation = new AWS.CloudFormation();
...
```

where `work-account` is my profile name

**Comment by kahouieong** [comment]
Do you get any errors? How about if you provide a profile name which doesn't exist?

**Comment by alanwill** [comment]
The error I'm getting is:

`An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.`

It sounds like it's still trying to get to the default profile because I did delete that key. I get the same error if I use a correct profile name or an incorrect one.

**Comment by kahouieong** [comment]
You also need to update the script inside [package.json](https://github.com/awslabs/aws-api-gateway-developer-portal/blob/9f14722fff677895e1c248d6aabd9dd7ea990626/package.json) to use profile as well.

**Comment by alanwill** [comment]
Ah yes that's what was missing, it all works now. Thanks a lot for your help!
