### ISSUE TITLE
generated WebsiteUrl incorrect

### ISSUE THREAD

**Issue by danPudwellUK** [awslabs/aws-api-gateway-developer-portal#151]
The generated url is:
http://{DevPortalSiteS3BucketName}.s3-website-{region}.amazonaws.com

it should be:
http://{DevPortalSiteS3BucketName}.s3-website.{region}.amazonaws.com

cloudformation/template.yaml needs changing on line 917.  The last '-' should be a '.'

**Comment by Trial-In-Error** [comment]
Ahh, what region are you in?

Unfortunately, s3 offers website URLs in [two formats](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html) depending on the region. I believe the template currently uses the format used in us-west-2, but I don't know offhand which other regions use which format.

I think this issue should remain open to track adding logic to determine which format to use in the template.

**Comment by danPudwellUK** [comment]
I was in eu-west-2

**Comment by a-tan** [comment]
Here's the specific mapping: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints

**Comment by a-tan** [comment]
This bug has implications on refresh as well.
Repro:
1) Deploy a dev portal in a region that uses a . instead of - (like us-east-2 or eu-west-2)
2) Clicking WebsiteURL from the template won't work (this is the issue mentioned initially)
3) Change URL to a ., dev portal will work
4) Refresh
5) Dev portal URL will revert back
