### ISSUE TITLE
productCode tied to one usage plan?

### ISSUE THREAD

**Issue by orasis** [awslabs/aws-api-gateway-developer-portal#18]
From what I understand, when a purchase is made on the marketplace, the subscriber is tied to a single usage plan.  Since the API is pay per request, initially I'd like to keep the customer at a reasonable request limit so they don't rack up a huge bill and then not pay.  Over time as they've shown an ability to pay I'd like to move them up to a higher limit.  However, since their subscription is tied to the initial usage plan this doesn't seem possible.  

To get around this, it seems we could create a new usage plan/product code combination and somehow only give that customer access to it?  But, then it seems that their old API key wouldn't migrate, which is a non-starter since the API key may be embedded in mobile app deployed in the wild.

Hopefully I'm misunderstanding the whole thing and the productCode isn't actually used for metering?  Could it be that I can just move a subscribed customer to a new usage plan?  Or can I have multiple usage plans with the same product code to get around this?

**Comment by vitalii-budkevych** [comment]
The combination of API key to usage plan to API stage has to be unique otherwise things would get ambiguous. To solve your problem you can add customer's API key to different usage plan after the initial period, but then you'd have to redirect the customer to a different stage or different API as you can't have 2 usage plans with the same key applied on the same API stage. Better solution might be to remove the key from the initial usage plan after the initial period and add it to the "extended" usage plan on the same API stage so the customer or mobile app code won't even know that the change has happened.

**Comment by rpgreen** [comment]
Correct. Create a second usage plan for the API, update the product code on that usage plan, remove the customers key from the first usage plan, and add it to the second usage plan.

**Comment by orasis** [comment]
Just to be clear. Can you have the same product code on more than one usage
plan? Or does the second usage plan need to have a new product code? Or
does the product code not really matter if you have correct customerId on
the API key?

**Comment by rpgreen** [comment]
Yes, as long as a single API key is only subscribed to one usage plan with the same API / product code (which API Gateway enforces anyway).

All usage plans with that product code will get metered to the marketplace product associated with that product code. 

In any case, I'd encourage you to do your own testing around this.
