### ISSUE TITLE
Deep linking to API documentation pages (or any sub page).

### ISSUE THREAD

**Issue by Sylistron** [awslabs/aws-api-gateway-developer-portal#21]
Funny enough, the AWS Marketplace listings like to have deep links to things like the API documentation, just to make customer lives easier.  

Please provide a way to add a deep link to an API.

**Comment by flofu** [comment]
I have deployed the Developer Portal using the setup script to <BucketName> and <Region>.

After the setup script finished, I was redirected to
http://<BucketName>.s3-website-<Region>.amazonaws.com/
This fails because the URL is not correct.

Expected: http://<BucketName>.s3-website.<Region>.amazonaws.com/
(note the . instead of - before <Region>)

I can manually fix that and access and navigate http://<BucketName>.s3-website.<Region>.amazonaws.com/

However, as soon as I enter a path directly, such as http://<BucketName>.s3-website.<Region>.amazonaws.com/api, I get redirected to the incorrect domain again (http://<BucketName>.s3-website-<Region>.amazonaws.com/api) and cannot access this page.

This makes it impossible to share any URL to the Developer Portal except /.

Is this the same issue as above?
Isn't there a simple fix, which you can suggest?

**Comment by brettstack** [comment]
I believe the issue here was that @Sylistron was using Cloudfront to serve the UI. This is totally reasonable (and likely preferred); I believe his PR #22 solved his issue. We will look into supporting CloudFront as default. Thanks again for your PRs.
