### ISSUE TITLE
Routing is broken after flipping to HTTPS

### ISSUE THREAD

**Issue by nsellers** [awslabs/aws-api-gateway-developer-portal#258]
I am still using version 1 of the portal and am in the process of migrating to version 2. We recently changed from http to https and now if a user hits refresh on their browser when they are anywhere besides the main page they get: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>getting-started</Key>
<RequestId>FA298D5DFC726F1B</RequestId>
<HostId>
8Qs82AEE4bew7lW0sTUVWI9LDfnYbog8ShOqV8J7S74tR/yKyqehG5DeJUsMIbvva5lB9GzbClk=
</HostId>
</Error>

I did find in the express-server.js file in the Lambdas\backend folder the line where I need to change the domain and baseURL even if I update those to https we are still seeing the issue. Does the portal have a way to handle this or do I need to work on setting up isomorphic rendering and having the server also be able to handle the rendering? Any help would be great as this is making the site look unstable. Thanks!!!

**Comment by nsellers** [comment]
This is returning a 404. If you want to check it out for yourself please go to https://developer.newforma.cloud which will work then if you try to go directly to https://developer.newforma.cloud/updates it is broken.

**Comment by Trial-In-Error** [comment]
Hey! Visiting https://developer.newforma.cloud/updates appears to work now - looks like you've got it figured out! For other visitors with similar issues, the dev portal has been hosted at various points on an S3 website URL, an S3 bucket URL, and an S3 bucket URL fronted by CloudFront. The "NoSuchKey" error from above is an S3 error from trying to fetch a file (instead of index.html) that doesn't exist. The solutions to this are:
- If you're on a version of the dev portal hosted on an S3 website URL, configure the routing rules for it to map 403s to return index.html
- If you're on a version of the dev portal hosted on an S3 bucket URL, upgrade to a version where the S3 bucket URL is fronted by CloudFront
- If you're on a version of the dev portal hosted by CloudFront in front of an S3 bucket URL, configure the CloudFront distribution's CustomErrorResponses [to return index.html](https://github.com/awslabs/aws-api-gateway-developer-portal/blob/master/cloudformation/template.yaml#L1399)

Either way, good job on getting it working for your use case, and I love the custom style/theme! Let us know if you have any other feature requests or questions. Oh, and are you using the [customization options](https://github.com/awslabs/aws-api-gateway-developer-portal/wiki/Customization) we provide? It looks like you (likely) have a significantly more complex use case than the built-in customization was intended to support.
