### ISSUE TITLE
DevMode portals don't have a functional route for index.html

### ISSUE THREAD

**Issue by markcarroll** [awslabs/aws-api-gateway-developer-portal#260]
1. Create a new stack with DeploymentMode=true
2. Go to the S3 hosted URL emitted by CF
3. Get Page Not Found on screen

**Comment by markcarroll** [comment]
It looks like this also messes up the `config.js` creation.  Since the `write-config.js` script reads the URL output from CF and then tries to add `/config.js` to it, this no longer works.

**Comment by Trial-In-Error** [comment]
What URL are you seeing as a stack output?

**Comment by markcarroll** [comment]
Don't have it available now, but the URL I got was the S3 bucket URL root. However, going there didn't work. It came up with the nav bar and Page Not Found in the main content area.  Clicking on the logo top left changed to the correct page.  
Sorry, I switched away from DevMode so not able to repro right now.

**Comment by Trial-In-Error** [comment]
So, the URL that the stack outputs is something like: `https://STACK-NAME.s3.us-west-2.amazonaws.com/index.html`. The index.html is necessary, because the S3 bucket doesn't have routing rules (like CloudFront's default object or S3 website bucket's static page). Unfortunately, the single-page webapp doesn't have a route for index.html, so it serves the 'not found' page. The best workaround for this is probably to add a route for index.html to the SPA.

Work items this issue tracks:
- Add a route for /index.html to the SPA
- Fix write-config to work with the S3 URLs

**Comment by alex-chew** [comment]
@markcarroll - The issue should be fixed by #282, with the caveat that page refresh and deep linking still do not work. If you are still experiencing the problem, please feel free to re-open the issue.

**Comment by nhy1210** [comment]
Page refresh and open in new tab or window are not found. I enable the S3 static web hosting and get this done but can not sign in because of the callback URL problem with Cognito. Any suggestions are much appreciated.
