### ISSUE TITLE
"Try it Out" does not work

### ISSUE THREAD

**Issue by jflevi** [awslabs/aws-api-gateway-developer-portal#50]
Hi have successfully created my portal with my own APIs and I can navigate in all the methods.

For all the method when I press the "Try it Out" button I always get 

Response code 0 and
Response Headers {
  "error": "no response from server"
}

If I copy the generated curl command and execute it it works fine.

Any idea how I could fix this?

Thanks
JF

![try it out](https://user-images.githubusercontent.com/19683809/26971029-e9a9ec70-4d0b-11e7-840d-706fad3db073.png)

**Comment by brettstack** [comment]
What does that url (ending /print/123) return? If I hit an endpoint which returns HTML, I get the same result you get. However, If I hit an endpoint which returns JSON, it outputs correctly.

This is likely a Swagger UI issue.

**Comment by jflevi** [comment]
Hi,

The end point returns JSON . The expect JSON flow for this API call

{"message":"Could not print policy:123","codeBackOffice":34039,"messageBackOffice":"The policy(123) is not found."}
Expected HTTP Status is 400

So I don't understand why response body is empty and response header and where No response from server come from.

with following curl command:
curl --header "x-api-key: WGOQtX0SPn9T6v7dwgEkY7jd9vX5d7dR4voI2nNx" -X GET https://nclwa81dse.execute-api.eu-central-1.amazonaws.com/integration/v1/policies/print/123

Thanks

JF

**Comment by brettstack** [comment]
I believe "No response from server" is coming from Swagger.

Based on this issue https://github.com/swagger-api/swagger-ui/issues/2945#issuecomment-296211503 I believe this to be a CORS issue. Can you open up your browser dev tools and check the console to see if you get a CORS issue? If you do, you will need to configure your API to be accessible from that URI.

**Comment by brettstack** [comment]
I just tried it on mine. The reason I was getting it on the HTML response was indeed because that endpoint was not CORS-enabled.

**Comment by jflevi** [comment]
It seems to be the point, I have the following message from the console:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nclwa81dse.execute-api.eu-central-1.amazonaws.com/integration/v1/policies/print/123. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Could you please explain how to set-up CORS?
Thanks

**Comment by brettstack** [comment]
MDN will do a better job than I could https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS.

**Comment by theironcook** [comment]
I had a similar problem with the simple PetStore API example as soon as I required an API key on each level of the resources.  As soon as I deployed this requirement I started seeing this type of behavior.  Along with this type of error in Cloud Watch.

(99762de6-5792-11e7-aa12-bde9187b092d) API Key not authorized because method 'GET /pets' requires API Key and API Key is not associated with a Usage Plan for API Stage hsn6gb4zul/Dev: API Key was required but not present

I added the x-api-key header parameter to my curl requests and things started working again...
curl -X GET --header 'Accept: application/json' --header 'x-api-key: xxx' 'https://xxx.execute-api.us-east-1.amazonaws.com/Dev/pets'
 
I tried to add the x-api-key as a parameter to my swagger defs and it appeared to work. 
/pets:
    get:
      tags:
      - "pets"
      summary: "List all pets"
      produces:
      - "application/json"
      parameters:
      - name: "x-api-key"
        in: "header"
        description: "The x-api-key for security"
        required: false
        type: "string"

 At least I could see the new variable in the docs and when I entered a key and clicked "Try It" I could see the curl request looked correct.  But unfortunately, I still see the same error in Cloud Watch and see the same behavior of no results returned.  It appears like the code in the developer portal doesn't include the x-api-key into the requests for some reason.  I also tried to create accounts in the developer portal - I can see the new API Keys in the AWS Gateway API console and the new API key is valid.  Alas, the developer portal does not include the x-api-key in the request header when I click on the "Try It" button :(

**Comment by brettstack** [comment]
@theironcook are you adding your API Key as described in this blog https://aws.amazon.com/blogs/compute/generate-your-own-api-gateway-developer-portal/

> Next click the red alert icon, enter your API Key, and click Authorize. Finally, click the “Try it out!” button on any of your resources to make a request to your live API.

**Comment by brettstack** [comment]
I believe this option to enter your API Key shows when you set API Key Required on the method. Deploy your API, then export your Swagger. On the method where you set API Key Required, you should see in the Swagger:

```yaml
      security:
      - api_key: []
```

Add this to your developer portal and package-deploy. This option should now show.

**Comment by theironcook** [comment]
@brettstack Thank you very much.  I didn't notice the little red icon.  I took out my own definition for the x-api-key header and redeployed everything.  I login, extract the api key via the "Show API Key" in the top right of the UI, copy the API key, click the little red icon next to my request, enter in the API key, the little red icon changes to a little blue icon.  I then click the "Try it out!" button - at this point I can see the CURL request is good - I can see the x-api-key header and the curl command works.  Unfortunately, I get nothing back from the server, 0 content and a response header of error: no response from server still.  When I look at the actual Ajax call generated in the Chrome network console, I don't see the x-api-key in the request header.  Is there possibly a bug in the swagger UI code?

**Comment by theironcook** [comment]
Here's some more info on the ajax request I see in the Chrome network console that is generated when I click the "Try it now!" button:
  Request URL:https://hsnxxx.execute-api.us-east-1.amazonaws.com/Dev/pets
  Request Method:OPTIONS
  Status Code:403 
  ...
Request Headers
  :authority:hsnxxx.execute-api.us-east-1.amazonaws.com
  :method:OPTIONS
  :path:/Dev/pets
  :scheme:https
  accept:*/*
  accept-encoding:gzip, deflate, br
  access-control-request-headers:x-api-key
  access-control-request-method:GET
  origin:http://ascend-api.s3-website-us-east-1.amazonaws.com
  referer:http://ascend-api.s3-website-us-east-1.amazonaws.com/apis/hsnxxx

I'm confused by a few things - why was the http method an OPTIONS instead of a GET.  And I'm confused why I don't see a request header named "x-api-key" with a value that is the key.

I've been trying to just get the simple Pet Store example working.  It works well until I specify that an api key is required on my API Gateway resources.  Then, manual Curl or Postman works but not the developer portal.

**Comment by theironcook** [comment]
You can test this on my pet store sample portal if you'd like:
http://ascend-api.s3-website-us-east-1.amazonaws.com/apis/lx78mgot0b#!/default/get_pets

Use the API key RZVoQV3ffC478ZUdJz90D84sHriYB0XR3xwdWIld.  You will see that the curl command works just fine but the command running through the swagger-ui does not work and no results are returned.

**Comment by brettstack** [comment]
The `OPTIONS` call is known as the pre-flight request in CORS. Once you configure CORS correctly, you should see the x-api-key header be sent in the following GET request.

**Comment by theironcook** [comment]
@brettstack Thank you very much for the help.  Yes, the problem was that my Gateway API wasn't configured to use CORS.  These docs also helped me: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

All I really had to do was to click on API's Resource and click Action > Enable CORS.
Everything works now with the API keys enabled.

I did notice that after a few times of creating / deleting my stack via the setup / delete-stack that certain items aren't cleaned up.  Like my IAM Lambda roles weren't properly handled and my API wasn't properly cleared out.  So, I did need to manually delete quite of bit of stuff - but I realize this is a reference program and not really meant for that kind of abuse.  Thank you very much for the help.

**Comment by brettstack** [comment]
Glad it's working. You shouldn't need to delete and recreate the stack everyone. Running `npm run package-deploy` for the server and `npm run upload-site` should suffice.

**Comment by simonfranzen** [comment]
I am also facing the same problem. CORS is enabled in my Gateway API (playing around with the PetStore example). I setup API key access and exported a fresh Swagger JSON&YAML. I added these to the project, packed & deploy & upload-site. The request to the API still works only with curl in my CLI and not with the UI of the developer portal.

I think I got a step further. I am getting a correct forbidden without the API key, but including the key I still getting a "no response from server"

**Comment by Trial-In-Error** [comment]
Hi! We have a new version of the developer portal on master that moved from using swaggerui 2 to swaggerui 3; this likely fixed this bug. I'm closing this; if you have any issues with the new developer portal, please open a fresh issue. Thanks!
