### ISSUE TITLE
ResourceConflictException  error when deploy api-gateway-dev-portal

### ISSUE THREAD

**Issue by mahadevancloudmaster** [awslabs/aws-api-gateway-developer-portal#523]
Getting below error when deploy api-gatewa-dev-portal, how to fix it?
ERROR	Error occurred: ResourceConflictException: The operation cannot be performed at this time. The resource arn:aws:lambda:us-east-1:837769957138:function:serverlessrepo-agdp-CloudFormationEdgeLambda-V0ryMWIW7oGj is currently in the following state: 'Pending'. StateReasonCode: 'Creating'
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'ResourceConflictException',
  time: 2021-12-22T16:49:08.973Z,
  requestId: 'b982a458-5ba5-4cca-bb4c-10a723df83a2',
  statusCode: 409,
  retryable: false,
  retryDelay: 29.651587960249913
}

above issue is already closed in https://github.com/awslabs/aws-api-gateway-developer-portal/issues/519

but still occuring

**Comment by lloypark** [comment]
Hello, the time stamps here coincide with an AWS outage in us-east-1. Could you confirm if you are still seeing this issue?

**Comment by mauritz-lovgren** [comment]
Getting the exact same error here, too. Makes it impossible to deploy the api dev portal (version 4.1.0).
Happens when creating CloudFrontSecurityHeadersSetup, gives `CREATE_FAILED` status with this reason:

`Received response status [FAILED] from custom resource. Message returned: The operation cannot be performed at this time. The resource arn:aws:lambda:us-east-1:072221712914:function:serverlessrepo-apidevport-CloudFormationEdgeLambda-CzH55f9eIwfL is currently in the following state: 'Pending'. StateReasonCode: 'Creating' For more details, see CloudWatch group (/aws/lambda/serverlessrepo-apidevport-CloudFrontSecurityHeader-CzH55f9eIwfL) and stream (2022/01/12/[$LATEST]49a18cd11e174c049f015ef02e22996f) (RequestId: cabdc9cf-7c23-455b-bf0d-7acfb52996f9)`

The CloudWatch log contains the error output as shown by @mahadevancloudmaster above.

Could it be that the creation of the CloudFrontSecurityHeadersSetup is attempted _before_ the lambda function is fully created (hence the 'pending' state in the message) ?

**Comment by mauritz-lovgren** [comment]
Looks like the following commit on 4 Dec 2021 corrects this exact error? :

https://github.com/awslabs/aws-api-gateway-developer-portal/commit/56a75e44aa5fd9d566422e726daa0bf884a5dd3f#

**Comment by philcaixeta** [comment]
Hey! Thanks for sharing here.

I'm sorry for the delay, but we released a new version with the fix today =)
It will be live soon (Maybe in 30 mins), so you can try it again.

Thank you!
